name: "Haiku Art Generator"
description: "Generates haiku art"
inputs:
  PR_NUMBER:
    description: "Pull Request Number"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    PR_NUMBER: ${{ inputs.PR_NUMBER }}
